const provincias = [
    {
      id: 1,
      nombre: "Almería",
      coste_alojamiento: 12,
      coste_alimentacion: 22,
      imagen: "almeria.jpg",
    },
    {
      id: 2,
      nombre: "Granada",
      coste_alojamiento: 143.2,
      coste_alimentacion: 22,
      imagen: "granada.jpg",
    },
    {
      id: 3,
      nombre: "Sevilla",
      coste_alojamiento: 95,
      coste_alimentacion: 30,
      imagen: "sevilla.jpg",
    },
    {
      id: 4,
      nombre: "Málaga",
      coste_alojamiento: 120,
      coste_alimentacion: 35,
      imagen: "malaga.jpg",
    },
    {
      id: 5,
      nombre: "Cádiz",
      coste_alojamiento: 110,
      coste_alimentacion: 28,
      imagen: "cadiz.jpg",
    },
    {
      id: 6,
      nombre: "Córdoba",
      coste_alojamiento: 85,
      coste_alimentacion: 27,
      imagen: "cordoba.jpg",
    },
    {
      id: 7,
      nombre: "Jaén",
      coste_alojamiento: 60,
      coste_alimentacion: 20,
      imagen: "jaen.jpg",
    },
    {
      id: 8,
      nombre: "Huelva",
      coste_alojamiento: 70,
      coste_alimentacion: 25,
      imagen: "huelva.jpg",
    },
    {
      id: 9,
      nombre: "Madrid",
      coste_alojamiento: 200,
      coste_alimentacion: 50,
      imagen: "madrid.jpg",
    },
    {
      id: 10,
      nombre: "Barcelona",
      coste_alojamiento: 180,
      coste_alimentacion: 45,
      imagen: "barcelona.jpg",
    },
    {
      id: 11,
      nombre: "Valencia",
      coste_alojamiento: 130,
      coste_alimentacion: 40,
      imagen: "valencia.jpg",
    },
    {
      id: 12,
      nombre: "Bilbao",
      coste_alojamiento: 150,
      coste_alimentacion: 38,
      imagen: "bilbao.jpg",
    }
];
